Update index.html
opensourcediversity/opensourcediversity.org pull request #102
Opened 2020-08-24 06:02 UTC by shub-garg

Corrected a few language errors.

2021-05-21 20:30 UTC, ramyaparimi approved these changes
LGTM

2021-05-21 20:38 UTC, ramyaparimi requested changes

2021-05-21 20:38 UTC, ramyaparimi commented on index.html
> +					<p>We help encourage, and celebrate underrepresented people to contribute to open source projects and speak at conferences!</p>
Help and encourage are two different efforts in this particular context. Please separate them with a comma.

2021-05-21 20:38 UTC, ramyaparimi commented on index.html
> +					<p>3 month long Open Source program during summers, to help beginners get started with Open Source Development while encouraging diversity.</p>
adding 'with an aim' really emphasizes the idea to encourage beginners. May be adding back to the sentence makes it more specific of the goal.

2023-06-15 12:45 UTC, jonatoni commented
@shub-garg hey :wave: will you be able to update the changes requested by @ramyaparimi please?

2024-05-29 00:25 UTC, closed without merging