solved the error Contributor Code of Conduct - Link - Error #148 :
opensourcediversity/opensourcediversity.org pull request #150
Opened 2023-04-29 15:33 UTC by Shu12388y

2023-04-29 18:00 UTC, BeginArjun reviewed
I think you should use this link instead https://github.com/opensourcediversity/opensourcediversity.org#-contribute-code-or-design.

2023-04-30 21:18 UTC, Roshanjossey requested changes
When the code of conduct was updated it was moved to here https://github.com/opensourcediversity/opensourcediversity.org/blob/main/.github/CODE_OF_CONDUCT.md

Also, could you please change it in Readme.md too? 
https://github.com/opensourcediversity/opensourcediversity.org/blame/main/README.md#L66

2023-04-30 21:18 UTC, Roshanjossey commented on index.html
> +				<p>Please note that Open Source Diversity has a <a href="https://github.com/opensourcediversity/opensourcediversity.org" target="_blank" rel="noopener">Contributor Code of Conduct</a> based on th
```suggestion
				<p>Please note that Open Source Diversity has a <a href="https://github.com/opensourcediversity/opensourcediversity.org/blob/main/.github/CODE_OF_CONDUCT.md" target="_blank" rel="noopener">Contributor Code of Conduct</a> based on the <a href="https://www.contributor-covenant.org" target="_blank" rel="noopener">Contributor Covenant</a>.<br>By participating in this project online or at events you agree to abide by its terms.</p>
```

2023-05-04 06:50 UTC, Roshanjossey approved these changes

2023-05-15 10:16 UTC, jancborchardt approved these changes
Looks good, thanks a lot! :)

2023-05-15 10:19 UTC, merged